version: '3.8'
services:
    dev:
        container_name: pokedex
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - '.:/usr/app'
          - '/usr/app/node_modules'
        ports:
            - '8080:8080'