FROM node:16.15.0-buster as build

WORKDIR /usr/share/react
COPY package*.json ./

RUN npm ci --only:production --silent

COPY . .

RUN npm run build

FROM nginx:1.22.0-alpine as prod

COPY --from=build /usr/share/react/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]