version: '3.7'
services:
    dev:
        container_name: pokedex
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/usr/pokedex'
            - '/usr/pokedex/node_modules'
        ports:
            - '8080:8080'